name: Package
on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - "v*"
  workflow_run:
    workflows: 
      - Test
    types:   
      - completed

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read chart info
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: read_yaml
        with:
          Chart.yaml: charts/foundryvtt/Chart.yaml
          
      - name: Install Helm
        run: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package chart
        run: helm package charts/foundryvtt -d foundryvtt-${{ steps.read_yaml.outputs['version']}}.tgz
      
      - name: Upload chart artefact
        uses: actions/upload-artifact@v4
        with:
          name: chart-release
          path: foundryvtt-${{ steps.read_yaml.outputs['version']}}.tgz
