name: Test
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint helm chart
        run: helm lint charts/foundryvtt
