name: Test
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - run: helm lint charts/foundryvtt
